spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/client-service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: client_storage
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /client-service-api.yaml
