spring:
  profiles:
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/client-service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: client_storage
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /client-service-api.yaml

client-service:
  security:
    jwt:
      secret-key: 4K2RJ9T6M8W3F5A7L1G0Y6P9V1E2X7C3Q5I8U2D5Z0H6B4N
      time-access: 600000
      time-refresh: 1800000
      time-session: 300000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
