name: Build-Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - developer
  merge_group:
    branches:
      - developer
jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Docker Containers
        run: docker-compose up -d

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build




